Sdpt 25
pravega/workshop-samples pull request #11
Opened 2019-08-26 09:54 UTC by chennv4

SDPT-25 DataGenerator added to parse CSV file to JSON. earthquake-database.csv file added in common resources

2019-08-26 09:57 UTC, chennv4 commented
@twincitiesguy 
SDPT-25 -- DataGenerator added to parse CSV file to JSON. 
earthquake-database.csv file added in common resources to use in workshop  samples
JSONWriter modified to use DataGenerator data.
Please review.

2019-08-27 13:53 UTC, chennv4 commented
@keedya 
SDPT-25 -- DataGenerator added to parse CSV file to JSON.
earthquake-database.csv file added in common resources to use in workshop samples
JSONWriter modified to use DataGenerator data.
Please review.

2019-08-30 13:08 UTC, keedya requested changes

2019-08-30 13:08 UTC, keedya commented on common/src/main/java/com/dellemc/oe/util/DataGenerator.java
> +        File csvFile =  new DataGenerator().getFileFromResources("earthquake-database.csv");
Can the file be a parameter that can be passed to this class instead of hardcoded value?

2019-08-30 13:08 UTC, keedya commented on common/src/main/java/com/dellemc/oe/util/DataGenerator.java
> +        File output = new File("c:/tmp/output.json");
This output only works on windows maybe? Does it need to be saved to FS?

2019-08-30 13:08 UTC, keedya commented on common/src/main/java/com/dellemc/oe/util/DataGenerator.java
> +        String jsonFile = "/tmp/earthquake-database.json";
why not keeping this data in memory?

2019-08-30 13:08 UTC, keedya commented on stream-ingest/src/main/java/com/dellemc/oe/ingest/JSONWriter.java
> +                            writer.writeEvent(routingKey, message);
need to get returned future here; `writeEvent` is an async function

2019-08-30 13:08 UTC, keedya commented on stream-ingest/src/main/java/com/dellemc/oe/ingest/JSONWriter.java
> +                            writer.writeEvent(routingKey, message);
see https://github.com/pravega/workshop-samples/blob/master/stream-ingest/src/main/java/com/dellemc/oe/ingest/EventWriter.java#L62-L63

2019-08-30 13:09 UTC, chennv4 commented on common/src/main/java/com/dellemc/oe/util/DataGenerator.java
> +        File output = new File("c:/tmp/output.json");
This is not required I will remove it

2019-08-30 14:01 UTC, chennv4 commented on common/src/main/java/com/dellemc/oe/util/DataGenerator.java
> +        File csvFile =  new DataGenerator().getFileFromResources("earthquake-database.csv");
added a Parameter for input file

2019-08-30 14:01 UTC, chennv4 commented on common/src/main/java/com/dellemc/oe/util/DataGenerator.java
> +        File output = new File("c:/tmp/output.json");
Removed output file

2019-08-30 14:02 UTC, chennv4 commented on common/src/main/java/com/dellemc/oe/util/DataGenerator.java
> +        String jsonFile = "/tmp/earthquake-database.json";
This is a unused helper method. Deleted the method

2019-08-30 14:03 UTC, chennv4 commented on stream-ingest/src/main/java/com/dellemc/oe/ingest/JSONWriter.java
> +                            writer.writeEvent(routingKey, message);
Good Point. Changed accordingly

2019-08-31 03:08 UTC, merged